// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SongBank.Models;

namespace SongBank.Migrations
{
    [DbContext(typeof(SongBankContext))]
    [Migration("20181121035025_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("SongBank.Models.SongItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Genre");

                    b.Property<string>("Height");

                    b.Property<string>("Title");

                    b.Property<string>("Url");

                    b.Property<string>("Width");

                    b.Property<string>("Youtube");

                    b.HasKey("Id");

                    b.ToTable("SongItem");
                });
#pragma warning restore 612, 618
        }
    }
}
